### PR TITLE
DRC Flow Support

### PR DESCRIPTION
**Pull request by dweight**
STL and STEP files for DRC Flow mount ware added.
This pull request adds:
- 30deg GoPro Hero 5/6/7
- model of a base fitting the frame
- typo fix in README

### CODE REVIEW

**Comment by theely** [comment]
Wow this is awesome, thanks for the contribution!

A few minor comments:

Design:
- The STL mount is missing the lens protection component. Could you add it? 

Naming Conventions:
- We should reference to the camera tilt degree in a consistent way. Either "deg" or "°". What's your preference?
- Step file should be renamed to "DRC Flow Mount (30°).step"

**Comment by dweight** [comment]
Thanks for the suggestions!
I'll fix the STL with lens protection, I totally forgot about that!
As for the naming convention, lets go with "°" symbol - I'll change it in the filenames.

**Comment by theely** [comment]
Awesome thanks for the contribution!

Just a side note, on this mount the GoPro is positioned on the very front. Is that a design decision?
The more advanced is the GoPro position the higher the risk fo damages.

**Comment by dweight** [comment]
> Awesome thanks for the contribution!
> 
> Just a side note, on this mount the GoPro is positioned on the very front. Is that a design decision?
> The more advanced is the GoPro position the higher the risk fo damages.

Answering your question, yes it is a design decision. I've modeled it with battery space in mind and it resembles the original GP session mount I've got with frame.

**Pull request merged**
